<?php
namespace App\Tests\Controller;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Liip\TestFixturesBundle\Test\FixturesTrait;

class ApplicationUrlsTest extends WebTestCase
{
    use FixturesTrait;

    private $fixtures;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->fixtures = $this->loadFixtures(['App\DataFixtures\AppTestFixtures'])->getReferenceRepository();
        }

    /**
     * @dataProvider provideUrls
     *
     * @param $url
     */
    public function testGetUrls($url)
    {
        $client = static::createClient();

        $client->request('GET', $url);

        $this->assertEquals(200 || 302, $client->getResponse()->getStatusCode());

    }

    public function provideUrls()
    {
        return [
            ['/'],
            ['new/application'],
            ['application/' . 1],
            ['update/application/' . 1],
            ['delete/application/' . 1]
        ];
    }
}