<?php

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use App\Entity\Application;

class ApplicationTest extends KernelTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        self::bootKernel();
    }

    public function getEntity()
    {
        return (new Application())
            ->setPositionTitle('test')
            ->setNotes('test')
            ->setCompanyName('test')
            ->setDate(new \DateTime());
    }

    public function hasError(Application $application, $count = 0)
    {
        $errors = self::$container->get('validator')->validate($application);

        $this->assertCount($count, $errors);
    }

    public function testValidEntity()
    {
        $this->hasError($this->getEntity(), 0);
    }

    public function testInvalidEntity()
    {
        $this->hasError($this->getEntity()->setCompanyName(''),1);
        $this->hasError($this->getEntity()->setPositionTitle(''), 1);
    }

    public function testTypeOfAttributes()
    {
        $this->assertIsString($this->getEntity()->getCompanyName());
        $this->assertIsString($this->getEntity()->getNotes());
        $this->assertIsString($this->getEntity()->getPositionTitle());
        $this->assertIsObject($this->getEntity()->getInterviews());
        $this->assertInstanceOf(DateTime::class, $this->getEntity()->getDate());
    }

}